language: rust
rust:
  - stable
# Need to cache the `.cargo` directory to keep .crates.toml for cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CXX=g++-5
    - os: osx
      env:
        - CXX=clang++
        - CXXFLAGS="-stdlib=libc++ "
before_script: 
  - (rustup component add rustfmt || true)
  - test "$TRAVIS_OS_NAME" != osx || export MACOSX_DEPLOYMENT_TARGET=10.7
