[package]
name = "clingo-rs"
version = "0.1.0"
authors = ["sthiele <sthiele78@gmail.com>"]
description = "Rust bindings to clingo C API"
build = "build.rs"
links = "clingo"

[lib]
name = "clingo"
path = "src/lib.rs"

[[example]]
name = "version"
path = "src/examples/version.rs"

[[example]]
name = "control"
path = "src/examples/control.rs"

[[example]]
name = "symbolic-atoms"
path = "src/examples/symbolic-atoms.rs"

[[example]]
name = "symbol"
path = "src/examples/symbol.rs"

[[example]]
name = "model"
path = "src/examples/model.rs"

[dependencies]
libc = "0.2.20"

[build-dependencies]
gcc = "0.3"
