[package]
name = "clingo"
version = "0.4.3"
authors = ["sthiele <sthiele78@gmail.com>"]
edition = "2018"
description = "Rust idiomatic bindings to the clingo library"
categories = ["api-bindings"]
license = "MIT"
repository = "https://github.com/potassco/clingo-rs"
documentation = "https://docs.rs/clingo"
readme = "README.md"
exclude = ["/.travis.yml"]

[badges]
travis-ci = { repository = "potassco/clingo-rs" }

[lib]
name = "clingo"
path = "src/lib.rs"

[features]
dynamic_linking = ["clingo-sys/dynamic_linking"]

[dependencies]
clingo-sys = "0.4.2"
rand = "0.6"
failure = "0.1"
failure_derive = "0.1"
bitflags = "1.0"



